services:
  api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:16-alpine
    container_name: rag-postgres
    environment:
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# test
# -  docker compose exec postgres psql -U rag_user -d rag_db -c "SELECT version();"